version: "2.2"

services:
  data_db:
    image: postgres:14.7
    container_name: "db.blurp.skelmis.co.nz"
    restart: always
    command: -p 2301
    ports:
      - "2301:2301"
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: data_skelmis_co_nz
      POSTGRES_USER: data_autohelp_db_user
      POSTGRES_PASSWORD: product-defeat-follow-worshiper-swimwear-drown
    volumes:
      - .db:/var/lib/postgresql/data
  data_web:
    image: ghcr.io/skelmis/blurp:master
    container_name: "web_blurp.skelmis.co.nz"
    restart: always
    ports:
      - "2300:2300"
    depends_on:
      - data_db
    cpus: 1
    mem_limit: 1g
    mem_reservation: 256m
    environment:
      SERVING_DOMAIN: "blurp.skelmis.co.nz"
      POSTGRES_HOST: db.blurp.skelmis.co.nz
      POSTGRES_DB: XXX
      POSTGRES_USER: XXX
      POSTGRES_PASSWORD: XXX
      POSTGRES_PORT: 2301
      PROD: 1

#networks:
#  default:
#    name: spook
#    external: true